### ISSUE TITLE
Not working with jquery 3.5.0

### ISSUE THREAD

**Issue by mksmanish79** [snapappointments/bootstrap-select#2435]
Not working with jquery 3.5.0

**Comment by Realex-fire** [comment]
hasOwnProperty is not a function in https://github.com/snapappointments/bootstrap-select/blob/109277978739609110543af7c70cab9ee7d22129/js/bootstrap-select.js#L3083

**Comment by Realex-fire** [comment]
hasOwnProperty is not a function
https://github.com/snapappointments/bootstrap-select/blob/109277978739609110543af7c70cab9ee7d22129/js/bootstrap-select.js#L3083

**Comment by ex1st** [comment]
@mksmanish79 #2430

**Comment by caseyjhol** [comment]
@mksmanish79 Please, next time, at least look at the 5 most recent issues before creating a new issue.
